---
- name: Install Utility VM's softwares
  hosts: all
  become: true
  vars:
      - skip: false


  tasks:

  
    # Git & System Setup
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/mssoftware
            state: directory
        - name: Checking out MS Software Archittecture Repo
          ansible.builtin.git:
            repo: 'https://github.com/MincomGithub/MS-Software-Architecture.git'
            dest: ~/mssoftware
        
      when: not skip|bool
      rescue:
        - name: rescue task that runs on setup fail
          ansible.builtin.debug:
            msg: "Task Rescued"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "Setup tasks done!" 

  

    # Duplicati
    - block:

        - name: Remove container
          community.docker.docker_container:
            name: duplicati
            state: absent

        - name: Re-create a duplicati container
          docker_container:
            name: duplicati
            image: lscr.io/linuxserver/duplicati:latest
            state: started
            detach: yes
            recreate: yes
            restart: yes
            restart_policy: always
            ports:
              - "8200:8200"
            volumes:
              - /appdata/config:/config
              - /backups:/backups
              - /source:/source
            env:
              MYSQL_ROOT_PASSWORD: "strong_password"
              PGID: "1000"
              TZ: "Etc/UTC"
              CLI_ARGS: " `#optional`"

        - name: Allow all access to 8200
          ufw:
            rule: allow
            port: 8200
            
      when: not skip|bool
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued duplicati"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - duplicati" 





