---
- name: Install Utility VM's softwares
  hosts: all
  become: true
  vars:
      - skip: false


  tasks:


  
    # Git & System Setup
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/mssoftware
            state: directory

        - name: Install Git
          apt:
            name: git
            state: present
            
        - name: Checking out MS Software Archittecture Repo
          git:
            repo: 'https://github.com/MincomGithub/MS-Software-Architecture.git'
            dest: ~/mssoftware
            
      rescue:
        - name: rescue task that runs on setup fail
          ansible.builtin.debug:
            msg: "Task Rescued"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "Setup tasks done!" 


    # Baserow
    # https://baserow.io/docs/installation/install-with-docker
    - block:

        - name: Remove container
          docker_container:
            name: baserow
            state: absent

        - name: Re-create a baserow container
          docker_container:
            name: baserow
            image: baserow/baserow:1.26.1
            state: started
            detach: yes
            recreate: yes
            restart: yes
            restart_policy: unless-stopped
            ports:
              - "80:80"
              - "443:443"
            volumes:
              - baserow_data:/baserow/data 
            env:
              BASEROW_PUBLIC_URL: "http://192.168.1.115"
              WEB_FRONTEND_PORT: "80"

        - name: Allow all access to 80
          ufw:
            rule: allow
            port: 80
            
      when: not skip|bool
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued baserow"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - baserow" 




    # plane
    # https://github.com/makeplane/plane?tab=readme-ov-file
    - block:
    
        - name: Docker command to pull down
          ansible.builtin.command:
            chdir: ~/
            cmd: git clone https://github.com/makeplane/plane.git 
        
        - name: Docker command to pull down
          ansible.builtin.command:
            chdir: ~/plane
            cmd: ./setup.sh

        - name: Docker command to pull down
          ansible.builtin.command:
            chdir: ~/plane
            cmd: docker compose -f docker compose-local.yml down

        - name: Docker command to pull up
          ansible.builtin.command:
            chdir: ~/plane
            cmd: docker compose -f docker compose-local.yml up -d


      when: skip|bool
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued plane"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - plane" 

