---
- name: Install Main VM's softwares
  hosts: all
  become: true

  tasks:

  
    # Git & System Setup
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/mssoftware
            state: directory
        - name: Checking out MS Software Archittecture Repo
          ansible.builtin.git:
            repo: 'https://github.com/MincomGithub/MS-Software-Architecture.git'
            dest: ~/mssoftware
            update: yes
        
      rescue:
        - name: rescue task that runs on setup fail
          ansible.builtin.debug:
            msg: "Task Rescued"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "Setup tasks done!" 




    # Homepage
    - block:
        - name: Creates homepage config directory
          ansible.builtin.file:
            path: ~/homepage/config
            state: directory

        - name: Tear down existing services
          community.general.docker_compose:
            project_src: ~/mssoftware/main/homepage
            state: absent

        # - name: Create and start services
        #   community.general.docker_compose:
        #     project_src: ~/mssoftware/main/homepage
        #   register: output

        # - ansible.builtin.debug:
        #     var: output

        # - name: Run `docker-compose up` again
        #   community.general.docker_compose:
        #     project_src: ~/mssoftware/main/homepage
        #     build: no
        #   register: output

        # - ansible.builtin.debug:
        #     var: output

            
    rescue:
      - name: rescue task that runs if any task fails inside block
        ansible.builtin.debug:
          msg: "Task Rescued Homepage"
          
    always:
      - name: This task always runs at the end regardless of outcome
        ansible.builtin.debug:
          msg: "This task will always run at the end - Homepage" 