---
- name: Install Utility VM's softwares
  hosts: all
  become: true
  vars:
      - skip: false


  tasks:

  
    # Git & System Setup
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/mssoftware
            state: directory
        - name: Checking out MS Software Archittecture Repo
          ansible.builtin.git:
            repo: 'https://github.com/MincomGithub/MS-Software-Architecture.git'
            dest: ~/mssoftware
        
      when: not skip|bool
      rescue:
        - name: rescue task that runs on setup fail
          ansible.builtin.debug:
            msg: "Task Rescued"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "Setup tasks done!" 



    # Restreamer
    - block:

        - name: Remove Restreamer's container
          community.docker.docker_container:
            name: restreamer
            state: absent

        - name: Re-create a restreamer container
          docker_container:
            name: restreamer
            image: datarhei/restreamer:latest
            state: started
            detach: yes
            recreate: yes
            restart: yes
            restart_policy: always
            ports:
              - "8080:8080"
              - "8181:8181"
              - "1935:1935"
              - "1936:1936"
              - "6000:6000/udp"
            volumes:
              - /opt/restreamer/config:/core/config
              - /opt/restreamer/data:/core/data \

        - name: Allow all access to 7102
          ufw:
            rule: allow
            port: 7102
            
      when: not skip|bool
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued restreamer"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - restreamer" 





