---
- name: Install Main VM's softwares
  hosts: all
  become: true

  tasks:


  
    # Git & System Setup
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/mssoftware
            state: directory
        - name: Checking out MS Software Archittecture Repo
          ansible.builtin.git:
            repo: 'https://github.com/MincomGithub/MS-Software-Architecture.git'
            dest: ~/mssoftware
            update: yes
        
      rescue:
        - name: rescue task that runs on setup fail
          ansible.builtin.debug:
            msg: "Task Rescued"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "Setup tasks done!" 


    # Netdata
    - block:

        # - name: Docker command to pull down
        #   ansible.builtin.command:
        #     chdir: ~/
        #     cmd: apt update
        
        # - name: Docker command to pull down
        #   ansible.builtin.command:
        #     chdir: ~/
        #     cmd: apt install netdata

        - name: Update all packages to their latest version
          ansible.builtin.apt:
            name: "*"
            state: latest

        - name: Install netdata (state=present is optional)
          ansible.builtin.apt:
            name: netdata
            state: present

        - name: Allow all access to 19999
          ufw:
            rule: allow
            port: 19999

        # Manual Edit IP to server's IP
        # 1. sudo vim /etc/netdata/netdata.conf
        # 2. systemctl restart netdata
        # 3. systemctl status netdata


            
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued netdata"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - netdata" 