---
- name: Install Utility VM's softwares
  hosts: all
  become: true
  vars:
      - skip: false


  tasks:


    # Git & System Setup
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/mssoftware
            state: directory

        - name: Checking out MS Software Archittecture Repo
          ansible.builtin.git:
            repo: 'https://github.com/MincomGithub/MS-Software-Architecture.git'
            dest: ~/mssoftware
        
      rescue:
        - name: rescue task that runs on setup fail
          ansible.builtin.debug:
            msg: "Task Rescued"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "Setup tasks done!" 


    # chatwoot
    # https://www.chatwoot.com/docs/self-hosted/deployment/docker/
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/chatwoot
            state: directory

        - name: Download the env file template
          ansible.builtin.command:
            chdir: ~/chatwoot
            cmd: wget -O .env https://raw.githubusercontent.com/chatwoot/chatwoot/develop/.env.example
        
        - name: Download the Docker compose template
          ansible.builtin.command:
            chdir: ~/chatwoot
            cmd: wget -O docker compose.yaml https://raw.githubusercontent.com/chatwoot/chatwoot/develop/docker compose.production.yaml

        - name: Docker command to pull down
          ansible.builtin.command:
            chdir: ~/chatwoot
            cmd: docker compose run --rm rails bundle exec rails db:chatwoot_prepare

        - name: Docker command to pull down
          ansible.builtin.command:
            chdir: ~/chatwoot
            cmd: docker compose up -d


      when: skip|bool
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued chatwoot"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - chatwoot" 



