---
- name: Install Utility VM's softwares
  hosts: all
  become: true

  tasks:


  
    # Git & System Setup
    - block:
        - name: Creates directory
          ansible.builtin.file:
            path: /root/mssoftware
            state: directory
        - name: Checking out MS Software Archittecture Repo
          ansible.builtin.git:
            repo: 'https://github.com/MincomGithub/MS-Software-Architecture.git'
            dest: ~/mssoftware
        
      rescue:
        - name: rescue task that runs on setup fail
          ansible.builtin.debug:
            msg: "Task Rescued"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "Setup tasks done!" 




    # passbolt
    - block:
        - name: Creates passbolt directory
          ansible.builtin.file:
            path: ~/passbolt
            state: directory

        - name: Docker command to pull down
          ansible.builtin.command:
            chdir: ~/mssoftware/utility/passbolt
            cmd: docker-compose down

        - name: Docker command to bring up
          ansible.builtin.command:
            chdir: ~/mssoftware/utility/passbolt
            cmd: docker-compose up -d

        - name: Allow all access to 7003
          ufw:
            rule: allow
            port: 7003
            
            
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued padloc"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - padloc" 



    # uptime kuma
    - block:

        - name: Remove container
          community.docker.docker_container:
            name: uptime-kuma
            state: absent

        - name: Re-create a redis container
          docker_container:
            name: uptime-kuma
            image: louislam/uptime-kuma:1
            state: started
            detach: yes
            recreate: yes
            restart: yes
            restart_policy: always
            ports:
              - "7003:3001"
            volumes:
              - uptime-kuma:/app/data

        - name: Allow all access to 7003
          ufw:
            rule: allow
            port: 7003
            
            
      rescue:
        - name: rescue task that runs if any task fails inside block
          ansible.builtin.debug:
            msg: "Task Rescued padloc"
            
      always:
        - name: This task always runs at the end regardless of outcome
          ansible.builtin.debug:
            msg: "This task will always run at the end - padloc" 


